Cleanup, remove echoes

diff --git a/.github/workflows/build_upon_pullrequest.yml b/.github/workflows/build_upon_pullrequest.yml
--- a/.github/workflows/build_upon_pullrequest.yml
+++ b/.github/workflows/build_upon_pullrequest.yml
@@ -92,6 +92,35 @@ jobs:
               fi
             done
             exit $status
+
+      - name: Check directory matches recipe name
+        if: ${{ steps.changed-recipes.outputs.changed_recipes != '' }}
+        run: |
+            echo "Check directory matches recipe name"
+            status=0
+            changed_recipes=$(echo "${{ steps.changed-recipes.outputs.changed_recipes }}" | xargs)
+            for recipe in $changed_recipes; do
+              grep -v '{' $recipe/meta.yaml > temp_meta.yaml
+              echo "grep $?"
+              if ! recipe_in_meta=$(yq '.package.name' temp_meta.yaml); then
+                echo "Failed to extract package name from $recipe/meta.yaml"
+                status=1
+                continue
+              fi
+              echo "yq $?"
+              echo "recipe_in_meta -$recipe_in_meta-"
+              recipe_dir=$(echo $recipe | sed 's+recipes/++' )
+              echo $?
+              echo "recipe_dir -$recipe_dir-"
+              echo "status $status"
+              if [[ "$recipe_dir" != "$recipe_in_meta" ]]; then
+                echo "Recipe directory is        : $recipe_dir"
+                echo "Recipe name in meta.yaml is: $recipe_in_meta"
+                echo "They should be the same."
+                status=1
+              fi
+            done
+            echo $?
             if [[ "$status" != 0 ]]; then
                 exit $status
             fi
@@ -118,6 +147,7 @@ jobs:
               for recipe_dir in ${{ steps.changed-recipes.outputs.changed_recipes }}; do
                 recipe=$(basename "$recipe_dir");
                 echo "  Recipe: $recipe"
+                # ls $CONDA_PREFIX/conda-bld/$dir
                 pkg=$(find "$CONDA_PREFIX/conda-bld/$dir" -name "$recipe-*.conda" | head -n 1)
                 echo "  Found package: $pkg"
                 if [ -n "$pkg" ]; then
